### ISSUE TITLE
Cluster rendering distance

### ISSUE THREAD

**Issue by bedzinsa** [googlemaps/android-maps-utils#121]
Is there any way to alter distance between markers when the cluster is rendered in order to increase accuracy of pointers?

**Comment by REWmitenko** [comment]
I've encountered the same problem. I copied and pasted the entire NonHierarchicalDistanceBasedAlgorithm.java file into a new algorithm class just so I could modify the MAX_DISTANCE_AT_ZOOM value. This isn't the preferred solution, but it works.

Perhaps this could be flagged and a setClusteringDistance(int dps) method could be put into the class? Or make the variable an accessible non-constant so that we could then extend the class and change it there?

**Comment by RobinCaroff** [comment]
Any update on this subject ?
The setClusteringDistance(int dps) method seems to be a good idea.

**Comment by Sofrosyn** [comment]
Still no answer to this issue. How do we set the cluster rendering distance

**Comment by Runman44** [comment]
Would also like this to happen :)

**Comment by Runman44** [comment]
I used the solution adressed above

`        algorithm = NonHierarchicalDistanceBasedAlgorithm<CustomClusterItem>().apply {
            maxDistanceBetweenClusteredItems = 50
        }
`
