### ISSUE TITLE
Is it possible to find a latlng on the polyline which is closest to another polyline?

### ISSUE THREAD

**Issue by abhilashlr** [googlemaps/android-maps-utils#147]
I have a scenario in which, we match the device latlng with the polyline with a tolerance of 150m. As a result the data stored onto the server isn't accurate as it has a deviation of 150m. 

Would like to know if there is a way in PolyUtil where, one finds whether the latlng is on the polyline using isLocationOnEdge(...) and if true then I obtain the latlng that was closest match (on the polyline) to the verified latlng.

**Comment by broady** [comment]
You could modify [PolyUtil.isLocationOnEdgeOrPath][1] to return the closest LatLng instead of `true`/`false`.

That's a very specific use case, and not one that I think the library should support.

[1]: https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/PolyUtil.java#L167

**Comment by abhilashlr** [comment]
Could you please provide more insights on which points should be returned? I would write a custom a method like you suggested.

**Comment by rohitsingh5** [comment]
can you tell me which points have you returned?

**Comment by myquery** [comment]
this is exactly what i have been trying to achieve, thanks for pointing to modifying the isLocationOnEdgeOrPath
