### ISSUE TITLE
Clustering animation too slow

### ISSUE THREAD

**Issue by MauriFont** [googlemaps/android-maps-utils#164]
The animation is too slow. When zooming in. after all markers move to their locations the cluster circle remains there like for 2 secs until it desappears.

**Comment by mnemonicflow** [comment]
@elfonte Do you have a big number of markers in a cluster?

**Comment by meierjan** [comment]
Is it possible that the unclustering happens on all markers - not only on those that are currently displayed? My memory jumps from 12mb straight to 30mb (around 1200 markers) when zooming in. This would explain why its getting slow. 

I will have a look into the code when I have some time.

**Comment by Libby713** [comment]
As one solution you can now choose to disable the animations, which was added in 27f7a5b

**Comment by cseh17** [comment]
Is there a solution for this issue? I have tried both with and without animation, and I still get the same result.

**Comment by danielgomezrico** [comment]
@Libby713 the issue persists even if you disable the animations, the clustering action looks ugly going from a lot of unclustered markers and they become clustered.

**Comment by daljeet33** [comment]
Would restricting the markers and therefore the clusters to only those visible within the viewport help? I am not sure if the animation currently is played out on all the cluster markers laid out on the map or only those that are within the viewport.

**Comment by jpoehnelt** [comment]
@daljeet33 That sounds like a possible cause worth investigating.

**Comment by barbeau** [comment]
I agree that restricting clustering to visible viewport may help.

Another possible fix is to move to the Maps SDK for Android v3.0.0 beta (instead of Play Services):
https://developers.google.com/maps/documentation/android-sdk/v3-client-migration

The release notes say that this bug for "Poor performance adding markers: each marker takes about 25ms on the UI thread" was fixed in that release:
https://issuetracker.google.com/issues/3582242

**Comment by barbeau** [comment]
Looks like @amuramoto started a transition to Android Maps SDK for Android v3 in this branch:
https://github.com/googlemaps/android-maps-utils/commits/android-sdk-v3-beta

@amuramoto Do you recall the current state of this branch, in terms of what's left to do?

**Comment by amuramoto** [comment]
The standalone v3 SDK is integrated in this branch, but since the SDK is still in beta we don't want to merge with master

**Comment by barbeau** [comment]
@amuramoto Thanks, makes sense.

**Comment by barbeau** [comment]
After digging into the library a bit more, it turns out there is already an implementation of a view-based clustering algorithm - `NonHierarchicalViewBasedAlgorithm`.

In the demo app, this is implemented in the [`VisibleClusteringDemoActivity`](https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/main/java/com/google/maps/android/utils/demo/VisibleClusteringDemoActivity.java), which is the "Clustering: 20k only visible markers" button in the UI:

![image](https://user-images.githubusercontent.com/928045/74545909-a9cf5200-4f17-11ea-8fc8-a2068c77d661.png)

When setting up `ClusterManager`, you can choose to use this algorithm:

```java
        DisplayMetrics metrics = new DisplayMetrics();
        getWindowManager().getDefaultDisplay().getMetrics(metrics);

        ...
        mClusterManager = new ClusterManager<>(this, getMap());
        mClusterManager.setAlgorithm(new NonHierarchicalViewBasedAlgorithm<MyItem>(
                metrics.widthPixels, metrics.heightPixels));
```

I modified `VisibleClusteringDemoActivity` to add 200,000 items and then tested performance on a Samsung Galaxy S8+ w/ Android 9 both with the default clustering algorithm, and then using `NonHierarchicalViewBasedAlgorithm`. There is a significant performance difference:
1. Default - When zoomed in the default algorithm quickly gets sluggish and can no longer render the re-clustering in real-time.
2. `NonHierarchicalViewBasedAlgorithm` - Continues to cluster and move markers in real-time.

After this testing, I'm fairly confident that anyone having clustering performance issues should be able to resolve them by using the `NonHierarchicalViewBasedAlgorithm`.

Please give that a shot and let us know how it goes!
