### ISSUE TITLE
Unnecessary separation from the official Maps SDK

### ISSUE THREAD

**Issue by eligrey** [googlemaps/android-maps-utils#179]
This library is not part of the official Maps SDK.

Why has this not been merged into the official SDK?

**Comment by broady** [comment]
This is a third party library.

**Comment by eligrey** [comment]
@broady If this is a third party library, who owns the copyright? I was unable to locate the copyright owner in https://github.com/googlemaps/android-maps-utils/blob/master/LICENSE#L190

**Comment by broady** [comment]
No official support from Google, or commitment to the API provided.

**Comment by eligrey** [comment]
Alright&hellip; Sounds like it belongs at <https://github.com/broady/android-maps-utils/>.

**Comment by broady** [comment]
Just to make it clear to anybody who might read this, there are many projects open sourced by Google which do not have official support.

Look at almost everything under @google, for example.

I'm closing this issue, and the other one you opened, because I'm almost certain you're not seriously interested in using this library. If you have serious concerns with the licensing of this project, then please contact me directly.
