### ISSUE TITLE
Overlapping of markers

### ISSUE THREAD

**Issue by quentin23soleil** [googlemaps/android-maps-utils#26]
When 2 markers are overlapping, clicking on one doesn't bring it foreground.

**Comment by summera** [comment]
@broady I found that the empty view was preventing many of the onMarkerClickListener events from firing. Also, the overlapped markers weren't coming to the front. This seems to work better for me. Any idea why?

```java
        map.setInfoWindowAdapter(new GoogleMap.InfoWindowAdapter() {
            @Override
            public View getInfoWindow(Marker marker) {
                // Empty info window.
                TextView textView = new TextView(getActivity());
                textView.setText(" ");
                return textView;
            }

            @Override
            public View getInfoContents(Marker marker) {
                return null;
            }
        });
```

**Comment by shaheerkhan12** [comment]
hey i really need to know if you can help with the logic ! condition: marker show and hide on zoom level as done in bookings.com maps view.... i came to know these markers show and hide on zoom level but if you look closely some of the markers hide because they overlap the other marker while zooming out so if you can help in teaching me how to  do that  or any kind of help that would be great

**Comment by barbeau** [comment]
@shaheerkhan12 You might get a quicker response on [StackOverflow with the tag `google-maps`](https://stackoverflow.com/questions/tagged/google-maps?tab=Newest). If you post there please link in this issue. Thanks!
