### ISSUE TITLE
Cluster items with exact same lat/lang position are always bound together as a cluster

### ISSUE THREAD

**Issue by usergoodvery** [googlemaps/android-maps-utils#384]
**Summary:** 
Cluster items with exact same lat/lang position are always bound together as a cluster and do not separate away as individual items even at the lowest zoom level.

**Steps to reproduce:** 
Add items with same lat/lang

**Expected behavior:** 
items should seperate

**Observed behavior:** 
items stay clumped together and rendered as cluster

**Device and Android version:** 
lib 0.4.3. Samsung Galaxy S6

**Comment by menismu** [comment]
I´ve developed a quick workaround, you can find [here](https://github.com/menismu/android-maps-utils/blob/master/demo/src/com/google/maps/android/utils/demo/ClusteringSameLocationActivity.java). 
In general, [ClusterManager](https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/clustering/ClusterManager.java) class is extended to include a method to check if markers in a cluster have the same location, if that´s the case, the implementation of [OnClusterClickListener](https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/clustering/ClusterManager.java#L278) distribute the markers around the cluster location an hides the original cluster.

This workaround only works if the user is in the maximum zoom level and all the markers in the cluster have exact the same location (lat/lng). Also, when the user zooms out all the markers bring back to the original cluster.

**Comment by barbeau** [comment]
Re-opening, there is a fix proposed in https://github.com/googlemaps/android-maps-utils/pull/413.

**Comment by agent10** [comment]
Has the same issue.

**Comment by september669** [comment]
Same problem with versions:
    implementation "com.google.android.gms:play-services-maps:18.0.0"
    implementation 'com.google.maps.android:android-maps-utils:2.2.3'

**Comment by barbeau** [comment]
Reading this issue again, it's not clear to me if the feature request is 1) to show clusters are individual markers (but still stacked on the same lat/lon), or 2) to somehow visualize markers with the same lat/lon as "unstacked" so they are separate and don't appear exactly on the same lat/lon.

@september669 @agent10 @menismu @usergoodvery Could you clarify which of the two above you're looking for?

If 1), you can actually accomplish this with the new method `shouldRender()` that was added in 2.3.0, along with `shouldRenderAsCluster()`. See the [`ZoomClusteringDemoActivity`](https://github.com/googlemaps/android-maps-utils/blob/main/demo/src/gms/java/com/google/maps/android/utils/demo/ZoomClusteringDemoActivity.java#L109) for an example, which implements a `ZoomBasedRenderer` that overrides these methods.

I tested this demo activity with the same marker locations as follows:

```
        clusterManager.addItem(new MyItem(18.545723, 73.797726, "Loc1", snippet));
        clusterManager.addItem(new MyItem(18.545723, 73.797726, "Loc2", snippet));
        clusterManager.addItem(new MyItem(18.545723, 73.797726, "Loc3", snippet));
        clusterManager.addItem(new MyItem(18.545723, 73.797726, "Loc4", snippet));
        clusterManager.addItem(new MyItem(18.545723, 73.797726, "Loc5", snippet));
        clusterManager.addItem(new MyItem(18.545723, 73.797726, "Loc6", snippet));
        clusterManager.addItem(new MyItem(18.545723, 73.797726, "Loc7", snippet));
```

...and when you zoom in you can see the individual markers instead of a cluster, although they are all stacked on top of each other. When you tap on the marker, it does cycle through all 7 of them and show the corresponding text in the popup balloon.

Please take a look and let me know if that accomplishes what you're looking for, or if you're looking for a solution to visualize markers with the same lat/lon in a different way.

**Comment by september669** [comment]
IMHO,  @menismu workaround above looks good and it will be a good UI solution.
I mean if you tap on cluster of markers with same location it splits around, and with zoom out splited markers clustered again.
