### ISSUE TITLE
[Question] - Is it possible to create a Cluster without context?

### ISSUE THREAD

**Issue by GuilhE** [googlemaps/android-maps-utils#441]
Hello,
Is it possible to create a Cluster without supplying the context?
 ```
public ClusterManager(Context context, GoogleMap map) {
        this(context, map, new MarkerManager(map));
}

public ClusterManager(Context context, GoogleMap map, MarkerManager markerManager) {
        this.mAlgorithmLock = new ReentrantReadWriteLock();
        this.mClusterTaskLock = new ReentrantReadWriteLock();
        this.mMap = map;
        this.mMarkerManager = markerManager;
        this.mClusterMarkers = markerManager.newCollection();
        this.mMarkers = markerManager.newCollection();
        this.mRenderer = new DefaultClusterRenderer(context, map, this);
        this.mAlgorithm = new PreCachingAlgorithmDecorator(new NonHierarchicalDistanceBasedAlgorithm());
        this.mClusterTask = new ClusterManager.ClusterTask();
        this.mRenderer.onAdd();
    }

```

The context is used only to create a DefaultClusterRenderer, it would be nice to have the possiblity to supply a desired Renderer. That way I could inject that render and create a cluster inside my ViewModel without injecting a Context into the ViewModel.

Well, my Activity is supplying the GoogleMap to the ViewModel, it could supply the ClusterManager and its render too...

```
@Override
public void onMapReady(GoogleMap map) {
    ...
    ClusterManager<...> clusterManager = new ClusterManager<>(this, map);
    clusterManager.setRenderer(new MyClusterRenderer(this, map, clusterManager));
    getViewModel().setupMap(map, clusterManager);
 }
```

**Comment by jeffdgr8** [comment]
I created a demo activity that utilizes a view model for clustering. https://github.com/googlemaps/android-maps-utils/pull/506 Instead of holding a reference to the `ClusterManager`, I hold a reference to the `Algorithm` in the `ViewModel` to be reused between configuration changes, since the `Algorithm` object is what holds the cluster item data. Besides the context through the `ClusterRenderer`, the `ClusterManager` also holds references to listeners, which are typically tied to the fragment or activity, as well as a `GoogleMap` instance, which is tied to the fragment or view.
