### ISSUE TITLE
Kml Overlay Display Placemark names without bubbles

### ISSUE THREAD

**Issue by owuor91** [googlemaps/android-maps-utils#460]
**Summary:** 
I want to overlay a kml file on a map and I expect names of placemarks to be displayed without bubbles

**Steps to reproduce:** 

Overlay a kml file with placemarks and points  and names onto a map

**Expected behavior:** 

Display the names of the places without the red bubbles

**Observed behavior:** 

The kml file is rendered with bubbles at the points where names ought to be displayed, the names are only displayed when the bubbles are clicked

**Device and Android version:** 
Tecno RA6 (Android 8.1.0 Oreo) stock ROM, 

OnePlus 5(Android 8.1.0 oreo) stock ROM

**Screenshots:** 

![screenshot_20180712-164558](https://user-images.githubusercontent.com/10431888/42639590-06c04698-85f9-11e8-80d2-11d57097c423.png) -Tecno RA6

![screenshot_20180712-172056](https://user-images.githubusercontent.com/10431888/42639651-35a14958-85f9-11e8-8977-761328d3bd66.jpg) -Oneplus 5

This is the same kml file rendered on google earth (names in yellow)
<img width="705" alt="screen shot 2018-07-12 at 17 31 33" src="https://user-images.githubusercontent.com/10431888/42639793-8a2c97a2-85f9-11e8-973a-af35d209cdfe.png">

**Comment by Zephyr2627** [comment]
can you give me the sample code for linestring display in map ?

**Comment by owuor91** [comment]
Hi @Zephyr2627 
Here is the sample code
`
@Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_maps);

    SupportMapFragment mapFragment = (SupportMapFragment) getSupportFragmentManager()
        .findFragmentById(R.id.map);
    mapFragment.getMapAsync(this);
  }

@Override
  public void onMapReady(GoogleMap ggleMap) {
    this.googleMap = ggleMap;
 try {
      KmlLayer kmlLayer = new KmlLayer(googleMap, R.raw.northarea, getApplicationContext());
      kmlLayer.addLayerToMap();
  } catch (Exception e) {
      e.printStackTrace();
  }

}
`

**Comment by owuor91** [comment]
Here is the kml file. Please rename extension to .kml
[northarea.txt](https://github.com/googlemaps/android-maps-utils/files/2370531/northarea.txt)

**Comment by VeenaHosur** [comment]
any solution you for this

**Comment by owuor91** [comment]
I used a hack. I extracted the points and names from the kml file and served them to the app as json. I then overlayed the KML file to only show the polygons. Afterwards I plotted the names onto the map as markers

**Comment by VeenaHosur** [comment]
if you have sample code can you share it Please

**Comment by owuor91** [comment]
This is the code for plotting the names as markers on the map
`public void displayLabels(GoogleMap googleMap, List<KmlPoint> kmlPoints) {
    markerList = new ArrayList<Marker>();

    for (KmlPoint kmlPoint : kmlPoints) {
      Bitmap txtBitmap = makeBitmap(context, kmlPoint.getName());
      if (kmlPoint.getCoordinates() != null) {
        String[] coordinatesArray = kmlPoint.getCoordinates().split(Constants.COMMA);
        String latitude = coordinatesArray[0];
        latitude = latitude.replace(Constants.DEGREE_SYMBOL, Constants.EMPTY_STRING).trim();
        String longitude = coordinatesArray[1];
        longitude = longitude.replace(Constants.DEGREE_SYMBOL, Constants.EMPTY_STRING).trim();
        MarkerOptions markerOptions =
            new MarkerOptions().position(new LatLng(Double.parseDouble(latitude), Double.parseDouble(longitude)))
                .icon(BitmapDescriptorFactory.fromBitmap(txtBitmap));

        Marker marker = googleMap.addMarker(markerOptions);
        markerList.add(marker);
      }
    }
  }`

**Comment by jeffdgr8** [comment]
The issue with this KML isn't with the name rendering. If you upload the same KML to [Google Maps](https://www.google.com/maps), it will also only display the names in an info window when clicked. There is an issue with the [star icon](http://maps.google.com/mapfiles/kml/shapes/star.png) not displaying though, which is why the default red bubble marker icons are displayed instead.

First of all, the bitmap isn't downloading. This is because the URL is http and not https, which is [required by default in Android 9+](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted).

But even after changing the URL to https, there is an issue with the icon not getting added to the markers because the code only checks for "Point" geometry types, and the geometry for the `KmlPlacemark`s is "MultiGeometry". It needs to recursively iterate over these multi-geometry `KmlPlacemark`s and check for "Point" sub-geometries.

I fixed this in https://github.com/googlemaps/android-maps-utils/pull/605 and confirmed the KML linked above renders correctly with the URL changed to https.
