### ISSUE TITLE
ClusterManager.clearItems() doesn't clear cache

### ISSUE THREAD

**Issue by g012** [googlemaps/android-maps-utils#578]
Hello,

When we clearItems in ClusterManager, it seems the markers cache of DefaultClusterRenderer is not cleared. Calling getMarker() on it will return a marker not matching the current Map, causing an exception.

I resorted to recreate the whole renderer on each clear to avoid that.

Thank you.

**Comment by jeffdgr8** [comment]
The only place `ClusterManager` updates `ClusterRenderer`'s markers is in the result of `cluster()` with the call to `onClustersChanged()`. So `clearItems()` doesn't actually update the map markers at all until `cluster()` is called. This is the same behavior as any of the `ClusterManager` methods that add or remove `ClusterItem`s, `addItems()`, `addItem()`, `removeItems()`, or `removeItem()`. All of these methods modify the `ClusterItem`s in the `Algorithm`, which will change what `Cluster`s are generated on the next call to `cluster()`. You should call `cluster()` after calling `clearItems()` and potentially any other methods afterwards to add or remove `ClusterItem`s from the map.

Could you elaborate more on what your code is doing and what exception is being thrown?

**Comment by barbeau** [comment]
@g012 While looking into https://github.com/googlemaps/android-maps-utils/issues/90 I can confirm that after calling `ClusterManager.clearItems()` there are markers remaining in `DefaultClusterRenderer`'s `mMarkerCache` cache, but this seems to be by design to allow updating the cluster markers without markers on the map flickering (which would happen if they were removed and then quickly re-added).

If you want to clear the map of all cluster markers, just do:

~~~
mClusterManager.clearItems();
mClusterManager.cluster();
~~~

I'm adding better Javadocs in a pull request I'm working on for https://github.com/googlemaps/android-maps-utils/issues/90 to describe this and related cases (as well as fixing an issue that prevented updating the marker contents from the cache).

I'm going to close out this issue, but if you can provide more information about the specific use case you're attempting with some sample code we can certainly revisit.
