### ISSUE TITLE
Cluster with markers in same location take default design

### ISSUE THREAD

**Issue by beli63** [googlemaps/android-maps-utils#655]
Hello,

I've update the library from 0.6.2 to 1.0.0 and I have a trouble with Cluster (Bug is not present in version 0.6.2)
I have Custom Cluster
When I have markers in same location, the Cluster take the default design and not mine

![Screenshot_1583853766](https://user-images.githubusercontent.com/5211719/76328298-6fc15800-62eb-11ea-9be7-ce6b8f091b5b.png)
![Screenshot_1583853778](https://user-images.githubusercontent.com/5211719/76328323-74860c00-62eb-11ea-9570-74959707c0d9.png)

**Comment by barbeau** [comment]
@beli63 Thanks for reporting this. Are you able to share code you used to create the above screenshot?

**Comment by beli63** [comment]
@barbeau , I use CustomMarkerClusteringDemoActivity Demo's code.
I just put same location in 2 Markers

**Comment by barbeau** [comment]
@beli63 Ok, thanks for the additional info. This may also be related to https://github.com/googlemaps/android-maps-utils/issues/384.

**Comment by beli63** [comment]
@barbeau Okay thanks

**Comment by nicemak** [comment]
still facing this bug in 1.0.2, any update?

**Comment by barbeau** [comment]
Sorry, no update yet!

**Comment by Joshgallagher** [comment]
I am also encountering this bug. By changing the algorithm to `GridBasedAlgorithm` it stops the default clustering icon from being shown. However, **this introduces other problems**.

I am not sure if there is anything erroneous occurring with the algorithms... hope that helps!

**Comment by B3nedikt** [comment]
A temporary fix would be to just overwrite "onClusterUpdated" with an empty implementation. Seems to fix the issue for me.

**Comment by androidovshchik** [comment]
@B3nedikt thanks. Fixed this problem

**Comment by beli63** [comment]
@B3nedikt Yes I valid, it fixed the problem
Thanks

**Comment by barbeau** [comment]
Looking at the code, it looks like this behavior is new in v1.0 due to a side-effect of PR https://github.com/googlemaps/android-maps-utils/pull/627, part of which fixes an issue with existing markers not reflecting updated contents. For example, as discussed in https://github.com/googlemaps/android-maps-utils/issues/90, prior to https://github.com/googlemaps/android-maps-utils/pull/627 if you updated a marker's position, title, or snippet, that update wouldn't be reflected on the map. 

PR https://github.com/googlemaps/android-maps-utils/pull/627 fixes this by updating the cached cluster marker using a new protected method `onClusterUpdated()`, whose default implementation uses the default design. So, when iterating through the markers to render them the 2nd identical location triggers `onClusterUpdated()` instead of `onBeforeClusterRendered()`, which then updates the marker with the default cluster design.

So, to fix this, you should override `onClusterUpdated()` as @B3nedikt suggested above, but the implementation should be the same as your `onBeforeClusterRendered()` implementation to avoid any caching issues.

Similarly, you should override the implementation of `onClusterItemUpdated()` with the same implementation as `onBeforeClusterItemRendered()`.

*An aside - the implementation can't be identical because you're working with a `Marker` instead of `MarkerOptions`, but it's as simple as changing from the format of `markerOptions.title("X")` to `marker.setTitle("X")`)*

**Comment by barbeau** [comment]
FYI, I've opened a pull request at https://github.com/googlemaps/android-maps-utils/pull/679 which shows the changes discussed above for the `CustomMarkerClusteringDemoActivity` in the demo app.

**Comment by andrewsafwatsamuel** [comment]
This occurs with me when zooming in and out

**Comment by barbeau** [comment]
Closed by https://github.com/googlemaps/android-maps-utils/pull/679
