### ISSUE TITLE
GoogleMap.OnMarkerClick with GeoJSON layer broken with 1.0.2

### ISSUE THREAD

**Issue by ryust** [googlemaps/android-maps-utils#677]
As the title indicates, after updating to 1.0.2 any registered onMarkerClick listeners no longer fire if there is a GeoJSON layer over the map. Works correctly with 0.5 and 0.6.2 releases.

**Comment by bartekpacia** [comment]
I also experience this bug.

**Comment by arriolac** [comment]
There have been some breaking changes since the 1.0.0 release. You can refer to the [changelog](https://github.com/googlemaps/android-maps-utils/releases/tag/1.0.0) for the full list. For this specific issue, take a look at the [MultiLayerDemoActivity](https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/main/java/com/google/maps/android/utils/demo/MultiLayerDemoActivity.java) to see how you can attached click events.

**Comment by arriolac** [comment]
Closing this issue. Feel free to comment or reopen if you still encounter issues.
