### ISSUE TITLE
How to use ClusterManager.updateItem() with hashCode and equals()

### ISSUE THREAD

**Issue by joknu1** [googlemaps/android-maps-utils#695]
#### Summary

`clusterManager.updateItem()` does not update item since `NonHierarchicalDistanceBasedAlgorithm` will not find item when `remove()` is called since `hashCode()` and `equals()` of updated item now returns different values.

#### Expected behavior
Not sure; maybe an `updateItem(T oldVale, T newValue)`
#### Observed behavior

Item was not updated and `updateItem()` returned `false`

#### Environment details

1. Sony Compact 
2. Android 9
3. android-maps-utils:1.1.0

#### Steps to reproduce

Reproduce in Demo app project:

  1. implement equals() and hashCode() in `TestingItem` in `com.google.maps.android.clustering.QuadItemTest`

        @Override
        public boolean equals(Object o) {
            if (this == o) {
                return true;
            }
            if (!(o instanceof TestingItem)) {
                return false;
            }
            TestingItem that = (TestingItem) o;
            return Objects.equals(mPosition, that.mPosition) &&
                    Objects.equals(mTitle, that.mTitle);
        }

        @Override
        public int hashCode() {
            return Objects.hash(mPosition, mTitle);
        }

  2. Then testAddRemoveUpdateClear will fail

**Comment by barbeau** [comment]
@joknu1 Thanks for raising this issue! Indeed, if you test for equivalence and implement hashcode on title and position, and then change one of those fields, the internal map won't be able to find that item when calling `updateItem()`.

`updateItem()` currently just wraps `removeItem()` and `addItem()`, so the workaround would be to call `removeItem()` with the unmodified item, then modify the item, then call `addItem()` with the modified item.

I'm wondering, though, if you consider an item with a different title to be the "same" item (i.e., you're trying to update it, rather than add a new item), should the title be included in the `.equals()` and `.hashCode()` methods?

For example, this passes the unit test:

```java
        @Override
        public boolean equals(Object o) {
            if (this == o) {
                return true;
            }
            if (!(o instanceof TestingItem)) {
                return false;
            }
            TestingItem that = (TestingItem) o;
            return Objects.equals(mPosition, that.mPosition);
        }

        @Override
        public int hashCode() {
            return Objects.hash(mPosition);
        }
```

**Comment by joknu1** [comment]
@barbeau  - Thanks for getting back on this!

I ended up using the workaround you mentioned. But now when looking at it again, and after reading your comments, I think I should have just implemented `.equals()` and `.hashCode()` differently. 

In my case `title` and `snippet` are `null`, since I implement my own `InfoWindowAdapter`, and only the position changes. But I have indeed other data, that uniquely could idently a `ClusterItem`, which I should've used instead.

I'm closing this issue.
