### ISSUE TITLE
Possibility clustering is integrated into maps sdk?

### ISSUE THREAD

**Issue by newmanw** [googlemaps/android-maps-utils#756]
I noticed you mentioned

> Maps SDK via Google Play Services (this library is not yet compatible with the Maps SDK v3.0 BETA library)

It's a bummer that a majority of these features are not available within the new version of the maps sdk.  With apple maps introducing clustering in iOS 11, and applications wanting visualize large amounts of geospatial data has there been any talk about integrating things like clustering into the maps sdk.

**Comment by barbeau** [comment]
@newmanw Whoops! Thanks for calling this out. The library does indeed work with Maps SDK v3.0 beta, but the docs you pointed to in the README just weren't updated - I'll fix this.

You can use this library with Maps SDK v3.0 beta with the following dependency:

```
dependencies {
    // Utilities for Maps SDK for Android V3 BETA
    implementation 'com.google.maps.android:android-maps-utils-v3:2.0.0'
}
```

**Comment by newmanw** [comment]
@barbeau, thanks for the response.  I was really asking if there are plans to merge portions or all of this utility library into  the maps sdk.  Sorry for the confusion

**Comment by arriolac** [comment]
Hi @newmanw, there currently are no plans with merging portions of the this into the Maps SDK. This is intentional as to keep the Maps SDK itself as lightweight as possible. Conversely, any additional maps-related feature that is useful only to smaller set of users (i.e. features in the utility library) will remain in the utility library. It's a balancing act between providing value and minimizing bloat. You can expect that this library will be maintained to

**Comment by arriolac** [comment]
Hi @newmanw, there currently are no plans with merging portions of the this into the Maps SDK. This is intentional as to keep the Maps SDK itself as lightweight as possible. Conversely, any additional maps-related feature that is useful only to smaller set of users (i.e. features in the utility library) will remain in the utility library. It's a balancing act between providing value and minimizing bloat. You can expect that this library will be maintained to be compatible with new developments of the Maps SDK though!

**Comment by newmanw** [comment]
@arriolac thanks, and I totally get minimizing bloat. With Apple recently adding clustering capabilities to its map sdk it seems like more and more apps are visualizing large amounts of geospatial data.  It is certainly nice to hear that the library is currently being maintained, however unless its part of the maps sdk its hard to assume this will always be the case.
