### ISSUE TITLE
Crash on com.google.android.libraries.places.widget.AutocompleteActivity

### ISSUE THREAD

**Issue by meenakshi-bharduwaj** [googlemaps/android-maps-utils#795]
One of my user randomly having this crash - java.lang.IllegalStateException: Cannot find the caller. startActivityForResult should be used.

Code snippet - 
zzft.zzb(Places.isInitialized(), "Places must be initialized.");
            if (zzc) {
                zzft.zzb(this.getCallingActivity() != null, "Cannot find caller. startActivityForResult should be used.");
            }

OS version - 9
Device - Samsung
Place Api version - com.google.android.libraries.places:places:2.4.0

**Comment by arriolac** [comment]
Since this issue is not related to the Maps SDK for Android Utility Library and instead for the Places SDK library, please either look at StackOverflow with the [google-places](https://stackoverflow.com/questions/tagged/google-places) tag or file an issue in the public [issue tracker](https://issuetracker.google.com/bookmark-groups/76561) if you believe this to be a bug within the SDK.
