### ISSUE TITLE
[V3] Zooming to markers' bounds causes markers to flicker

### ISSUE THREAD

**Issue by dkati** [googlemaps/android-maps-utils#827]
as described to title. 
This issue is NOT present at v2.

my marker creation is simple as
``` 

 MarkerOptions marker = new MarkerOptions()
                .position(Center)
                .title("My title");

   mMap.addMarker(marker);
```

Video link of reproduce: https://drive.google.com/file/d/1XqWK2mTFJly76l57OjGP0YOnT_N9MLxI/view?usp=sharing

i added some markers, and then, after some seconds i zoomed to projection like this ->
```

LatLngBounds.Builder builder = new LatLngBounds.Builder();
 for (Marker marker : mAllMarkers) 
              builder.include(marker.getPosition());
                
LatLngBounds bounds = builder.build();
CameraUpdate cu = CameraUpdateFactory.newLatLngBounds(bounds, 50);
 mMap.animateCamera(cu, 5500, null); // 5.5 seconds animation in order to show the flickering
```

my workaround is: add a unique z-index to every marker. That way it doesnt flicker BUT the order of markers is strange... you know what i mean

PS
Same flickering behavior while animating with hands, but since the zooming is limited, the flickering is rare

**Comment by barbeau** [comment]
@dkati Thanks for the info! Because this issue doesn't seem to be related to the android-maps-utils library but instead the Maps SDK v3 beta, could you please open this issue on the issue tracker for the Maps v3 beta SDK itself at https://issuetracker.google.com/issues/new?component=541018&template=1201436? The right people should see it there.

FYI, this actually looks similar to behavior I saw several years ago with the Maps SDK v2:
https://issuetracker.google.com/issues/35827028

I ended up attributing this to my app leaking fragments - I had accidentally had multiple instances of the SupportMapFragment when I only should have had one - see https://issuetracker.google.com/issues/35827028#comment7. After I fixed the fragment leak (although other things changed too) I no longer saw this problem. Not sure if you could have a similar issue.

**Comment by dkati** [comment]
Thanks for feedback @barbeau  . Although i didnt event touch the map fragment...i just migrate from v2 to v3
