### ISSUE TITLE
Support for EPSG:3857 coordinate system

### ISSUE THREAD

**Issue by appach22** [googlemaps/android-maps-utils#892]
I have a geojson file with EPSG:3857 coordinates, that is not supportet at the moment. It would be useful to add a support of different coordinate systems.
Below is the excerpt from the above mentioned file:
`{"crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::3857"}},"type":"FeatureCollection","features":[{"type":"Feature","properties":{"_id":1,"osm_id":"19910163","fclass":"residential","ref":null,"code":"5122","name":"Краснознамённая улица","maxspeed":"0","bridge":"F","oneway":"B","layer":"0","tunnel":"F","attaches":[]},"geometry":{"type":"MultiLineString","coordinates":[[[5004407.883815842,7021621.241789256],[5004504.998939607,7021691.389774981],[5004599.520319242,7021762.170350752],...`

**Comment by jpoehnelt** [comment]
Is this a static file? If so you can probably convert with [GDAL](https://gdal.org/) or similar tools. If it is not, the transformation from 3857 to EPSG:4326 is quite simple. Here is an example in https://gist.github.com/onderaltintas/6649521#file-meters2degrees-js. Might want to confirm the earth radius if you have slight inaccuracies.

**Comment by barbeau** [comment]
Generally, supposedly the Referencing component of GeoTools should be available for use without requiring the rest of the library - see:
https://gis.stackexchange.com/a/151569/12198

...which shows an example of the conversion:

```java
CoordinateReferenceSystem sourceCRS = CRS.decode("EPSG:4326");
CoordinateReferenceSystem targetCRS = CRS.decode("EPSG:25832");
MathTransform transform = CRS.findMathTransform(sourceCRS, targetCRS, false);
Geometry targetGeometry = JTS.transform( sourceGeometry, transform);
```

This StackOverflow Q&A is generally for Java and not specifically for Android, though. I'd be very curious if someone has tried this on Android, and if so if it works and what the APK size implications are, as it's been on my TODO list to try for a while.

**Comment by appach22** [comment]
These all great. The conversion itself is not a big problem. But imho the library that parses geojson should be able to work with different coordinate systems.

**Comment by jpoehnelt** [comment]
It is complicated to support transformations between different coordinate systems and the geojson specification calls this out. https://datatracker.ietf.org/doc/html/rfc7946#section-4

>The coordinate reference system for all GeoJSON coordinates is a
   geographic coordinate reference system, using the World Geodetic
   System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units
   of decimal degrees.  This is equivalent to the coordinate reference
   system identified by the Open Geospatial Consortium (OGC) URN
   urn:ogc:def:crs:OGC::CRS84.  An OPTIONAL third-position element SHALL
   be the height in meters above or below the WGS 84 reference
   ellipsoid.  In the absence of elevation values, applications
   sensitive to height or depth SHOULD interpret positions as being at
   local ground or sea level.

   >Note: the use of alternative coordinate reference systems was
   specified in [GJ2008], but it has been removed from this version of
   the specification because the use of different coordinate reference
   systems -- especially in the manner specified in [GJ2008] -- has
   proven to have interoperability issues.  In general, GeoJSON
   processing software is not expected to have access to coordinate
   reference system databases or to have network access to coordinate
   reference system transformation parameters.  However, where all
   involved parties have a prior arrangement, alternative coordinate
   reference systems can be used without risk of data being
   misinterpreted.
